// <auto-generated />
namespace OPUS.Data.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _308m2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_308m2));
        
        string IMigrationMetadata.Id
        {
            get { return "201608300727083_308m2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
