// <auto-generated />
namespace OPUS.Data.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1892016m4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1892016m4));
        
        string IMigrationMetadata.Id
        {
            get { return "201609180816283_1892016m4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
